aodraelgoat:
  extension: .svg
  output: build/aodraelgoat
debian:
  extension: .svg
  output: build/debian
linux-mint:
  extension: .svg
  output: build/linux-mint
arch:
  extension: .svg
  output: build/arch
dinosaur:
  extension: .svg
  output: build/dinosaur
ascii-cat:
  extension: .svg
  output: build/ascii-cat
squares:
  extension: .svg
  output: build/squares
pages_01:
  extension: .svg
  output: build/pages_01
pages_02:
  extension: .svg
  output: build/pages_02
hex-grid:
  extension: .svg
  output: build/hex-grid
gradients:
  extension: .svg
  output: build/gradients
