aodraelgoat:
  extension: .svg
  output: build/aodraelgoat
debian:
  extension: .svg
  output: build/debian
linux-mint:
  extension: .svg
  output: build/linux-mint
arch:
  extension: .svg
  output: build/arch
dinosaur:
  extension: .svg
  output: build/dinosaur
ascii-cat_1:
  extension: .svg
  output: build/ascii-cat_1
ascii-cat_2:
  extension: .svg
  output: build/ascii-cat_2
squares:
  extension: .svg
  output: build/squares
pages_1:
  extension: .svg
  output: build/pages_1
pages_2:
  extension: .svg
  output: build/pages_2
hex-grid:
  extension: .svg
  output: build/hex-grid
gradient_1:
  extension: .svg
  output: build/gradient_1
gradient_2:
  extension: .svg
  output: build/gradient_2
gradient_3:
  extension: .svg
  output: build/gradient_3
floral_1:
  extension: .svg
  output: build/floral_1
floral_2:
  extension: .svg
  output: build/floral_2
heart-chequerboard:
  extension: .svg
  output: build/heart-chequerboard
