aodraelgoat:
  extension: .svg
  output: build/aodraelgoat
debian:
  extension: .svg
  output: build/debian
linux-mint_1:
  extension: .svg
  output: build/linux-mint_1
linux-mint_2:
  extension: .svg
  output: build/linux-mint_2
arch_1:
  extension: .svg
  output: build/arch_1
arch_2:
  extension: .svg
  output: build/arch_2
arch_3:
  extension: .svg
  output: build/arch_3
dinosaur:
  extension: .svg
  output: build/dinosaur
ascii-cat_1:
  extension: .svg
  output: build/ascii-cat_1
ascii-cat_2:
  extension: .svg
  output: build/ascii-cat_2
squares:
  extension: .svg
  output: build/squares
hearts:
  extension: .svg
  output: build/hearts
pages_1:
  extension: .svg
  output: build/pages_1
pages_2:
  extension: .svg
  output: build/pages_2
hex-grid:
  extension: .svg
  output: build/hex-grid
gradient_1:
  extension: .svg
  output: build/gradient_1
gradient_2:
  extension: .svg
  output: build/gradient_2
gradient_3:
  extension: .svg
  output: build/gradient_3
floral_1:
  extension: .svg
  output: build/floral_1
floral_2:
  extension: .svg
  output: build/floral_2
heart-chequerboard:
  extension: .svg
  output: build/heart-chequerboard
clover:
  extension: .svg
  output: build/clover
triangles:
  extension: .svg
  output: build/triangles
